services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    command: php -S 0.0.0.0:9000
    ports:
      - 9000:9000

  db:
    image: mariadb:10.4.32
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - MYSQL_DATABASE=tennis_website
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes